### ISSUE TITLE
global name 'final_boxes' is not defined

### ISSUE THREAD

**Issue by Gaurav1302** [Timforce/tiny-tf#1]
While running the training script, following error is encountered.

File "./train_net.py", line 134, in <module>
    restore=bool(int(args.restore)))
  File "./lib/tiny/train.py", line 343, in train_net
    sw.train_model(sess, epochs, restore=restore)
  File "./lib/tiny/train.py", line 203, in train_model
    res = final_boxes[refind_idx, :]
NameError: global name 'final_boxes' is not defined

**Comment by Timforce** [comment]
Hi, 
**final_boxes** and **final_confidence** in **train.py**
should have been **boxes** and **scores** respectively.
```
if (len(boxes)>0):
    refind_idx = nms(boxes, scores, overlapThresh=cfg.TRAIN.NMS_Thresh)
    res = boxes[refind_idx, :]
    conf = scores[refind_idx, :]
```
I'll make sure to update the code, thanks for the feedback!

**Comment by Gaurav1302** [comment]
Thanks a lot! It works fine now.
