### ISSUE TITLE
does it work on a different dataset

### ISSUE THREAD

**Issue by baldmonkeey** [Timforce/tiny-tf#3]
Just wondering if we can use this on other classes (other objects in addition to faces)? How does it fare. Need to check if the authors have tried it first!

**Comment by Timforce** [comment]
Hi,
I haven't try it on other object classes, but i think it's certainly do-able. 
Though just want to mention, this network model really put a lot focus on finding 'tiny' faces.
If your goal is to find general objects without the need of the tiny stuff detection.
There are plenty of other robust and faster [object detection network](https://github.com/hoya012/deep_learning_object_detection) that may better fit your need.

**Comment by baldmonkeey** [comment]
Thanks! I am interested in tiny object detectors. Variations in objects of interest include deformation, aspect, scale.  Most single shot detectors do well on medium and large size objects. I am currently doing hierarchical detection, running single shot detectors on crops (sliding windows of original image with 20 %overlap).

**Comment by Jianyuyu5666** [comment]
Did anyone ever tried to train this model on multiple classes?
