### ISSUE TITLE
ImportError: No module named minibatch

### ISSUE THREAD

**Issue by sabrinatuli** [Timforce/tiny-tf#8]
Thanks for your tensorflow implementation. Whenever I do training I got this error. Could you please help me to fix it? 
![tiny_error](https://user-images.githubusercontent.com/11704586/56731895-355fd280-678e-11e9-8615-989e423406da.PNG)

**Comment by Timforce** [comment]
Hi,
Make sure there's **minibatch.so** in $tiny-tf/lib/roi_data_layer after you run:
```bash
python setup.py build_ext –inplace
rm -r build
```
If there's no such file, you probably need to debug the issue based on compiling error message.

**Comment by sabrinatuli** [comment]
I tried both of this command, but there is no such file name build and minibatch.so. I can't see any compile error. This is the message I get from there. Please take a look
![error](https://user-images.githubusercontent.com/11704586/56858561-91a13d00-69ae-11e9-8cd5-dd7b2ea5353f.PNG)

**Comment by Timforce** [comment]
Oops, my bad.
There needs to be **two** dashes before 'inplace', like this:
```bash
python setup.py build_ext --inplace
```
It sure is an easily neglected typo error.🤔

**Comment by sabrinatuli** [comment]
Thanks this issue is solved. It creates a build directory and a file named minibatch.o
